return {
  NeogitBranch = { fg = 'warning' },
  NeogitBranchHead = { fg = 'warning', bold = true },
  NeogitRemote = { fg = 'info' },
  NeogitObjectId = { fg = 'tertiary' },
  NeogitStash = { fg = 'quaternary' },
  NeogitTagName = { fg = 'info' },
  NeogitTagDistance = { fg = 'text_subtle' },
  NeogitStatusHEAD = { fg = 'primary', bold = true },
  NeogitFold = { fg = 'text_bright' },
  NeogitRebaseDone = { fg = 'success' },
  NeogitSectionHeader = { fg = 'tertiary', bold = true },
  NeogitSectionHeaderCount = { fg = 'info' },
  NeogitChangeAdded = { fg = 'success' },
  NeogitChangeModified = { fg = 'warning' },
  NeogitChangeDeleted = { fg = 'error' },
  NeogitChangeRenamed = { fg = 'warning' },
  NeogitChangeUpdated = { fg = 'quaternary' },
  NeogitChangeCopied = { fg = 'info' },
  NeogitChangeNewFile = { fg = 'success' },
  NeogitChangeUnmerged = { fg = 'error' },
  NeogitHunkHeader = { fg = 'text_secondary', bg = 'surface' },
  NeogitHunkHeaderHighlight = { fg = 'warning', bg = 'surface', bold = true },
  NeogitHunkHeaderCursor = { fg = 'warning', bg = 'surface', bold = true },
  NeogitDiffContext = { fg = 'text_secondary' },
  NeogitDiffContextHighlight = { fg = 'text', bg = 'surface' },
  NeogitDiffContextCursor = { fg = 'text', bg = 'surface', bold = true },
  NeogitDiffAdd = { fg = 'success' },
  NeogitDiffAddHighlight = { fg = 'success', bg = 'surface' },
  NeogitDiffAddCursor = { fg = 'success', bg = 'surface', bold = true },
  NeogitDiffDelete = { fg = 'error' },
  NeogitDiffDeleteHighlight = { fg = 'error', bg = 'surface' },
  NeogitDiffDeleteCursor = { fg = 'error', bg = 'surface', bold = true },
  NeogitDiffHeader = { fg = 'tertiary' },
  NeogitDiffHeaderHighlight = { fg = 'info', bold = true },
  NeogitDiffHeaderCursor = { fg = 'info', bold = true },
  NeogitActiveItem = { bg = 'surface' },
  NeogitFilePath = { fg = 'info' },
  NeogitCommitViewHeader = { fg = 'tertiary', bold = true },
  NeogitGraphAuthor = { fg = 'text_secondary' },
  NeogitGraphBlack = { fg = 'text_muted' },
  NeogitGraphBlackBold = { fg = 'text_muted', bold = true },
  NeogitGraphRed = { fg = 'error' },
  NeogitGraphRedBold = { fg = 'error', bold = true },
  NeogitGraphGreen = { fg = 'success' },
  NeogitGraphGreenBold = { fg = 'success', bold = true },
  NeogitGraphYellow = { fg = 'warning' },
  NeogitGraphYellowBold = { fg = 'warning', bold = true },
  NeogitGraphBlue = { fg = 'info' },
  NeogitGraphBlueBold = { fg = 'info', bold = true },
  NeogitGraphPurple = { fg = 'tertiary' },
  NeogitGraphPurpleBold = { fg = 'tertiary', bold = true },
  NeogitGraphCyan = { fg = 'quaternary' },
  NeogitGraphCyanBold = { fg = 'quaternary', bold = true },
  NeogitGraphWhite = { fg = 'text' },
  NeogitGraphWhiteBold = { fg = 'text', bold = true },
  NeogitGraphGray = { fg = 'text_subtle' },
  NeogitGraphBoldGray = { fg = 'text_subtle', bold = true },
  NeogitGraphOrange = { fg = 'primary' },
  NeogitSignatureGood = { fg = 'success' },
  NeogitSignatureBad = { fg = 'error' },
  NeogitSignatureMissing = { fg = 'tertiary' },
  NeogitSignatureNone = { fg = 'text_subtle' },
  NeogitSignatureGoodUnknown = { fg = 'success' },
  NeogitSignatureGoodExpired = { fg = 'warning' },
  NeogitSignatureGoodExpiredKey = { fg = 'warning' },
  NeogitSignatureGoodRevokedKey = { fg = 'error' },
  NeogitPopupSectionTitle = { fg = 'tertiary', bold = true },
  NeogitPopupBranchName = { fg = 'warning' },
  NeogitPopupBold = { bold = true },
  NeogitPopupSwitchKey = { fg = 'warning' },
  NeogitPopupSwitchEnabled = { fg = 'success' },
  NeogitPopupSwitchDisabled = { fg = 'text_muted' },
  NeogitPopupOptionKey = { fg = 'tertiary' },
  NeogitPopupOptionEnabled = { fg = 'success' },
  NeogitPopupOptionDisabled = { fg = 'text_muted' },
  NeogitPopupConfigKey = { fg = 'info' },
  NeogitPopupConfigEnabled = { fg = 'success' },
  NeogitPopupConfigDisabled = { fg = 'text_muted' },
  NeogitPopupActionKey = { fg = 'warning' },
  NeogitPopupActionDisabled = { fg = 'text_muted' },
  NeogitCommandText = { fg = 'text' },
  NeogitCommandTime = { fg = 'info' },
  NeogitCommandCodeNormal = { fg = 'success' },
  NeogitCommandCodeError = { fg = 'error' },
  NeogitFloatHeader = { fg = 'tertiary' },
  NeogitFloatHeaderHighlight = { fg = 'tertiary', bold = true },
}
