return {
  CinderMutedBackground = { fg = 'background' },
  CinderMutedContainer = { fg = 'container' },
  CinderMutedSurface = { fg = 'surface' },
  CinderMutedOverlay = { fg = 'overlay' },
  CinderMutedTextMuted = { fg = 'text_muted' },
  CinderMutedTextSubtle = { fg = 'text_subtle' },
  CinderMutedTextSecondary = { fg = 'text_secondary' },
  CinderMutedText = { fg = 'text' },
  CinderMutedTextBright = { fg = 'text_bright' },
  CinderMutedPrimary = { fg = 'primary' },
  CinderMutedSecondary = { fg = 'secondary' },
  CinderMutedError = { fg = 'error' },
  CinderMutedWarning = { fg = 'warning' },
  CinderMutedSuccess = { fg = 'success' },
  CinderMutedInfo = { fg = 'info' },
  CinderMutedTertiary = { fg = 'tertiary' },
  CinderMutedQuaternary = { fg = 'quaternary' },

  Normal = { fg = 'text', bg = 'background' },
  NormalNC = { fg = 'text', bg = 'background' },
  NormalFloat = { fg = 'text', bg = 'container' },
  FloatBorder = { fg = 'primary', bg = 'container' },
  FloatTitle = { fg = 'text_bright', bg = 'container', bold = true },
  FloatFooter = { fg = 'text_subtle', bg = 'container' },
  FloatShadow = { bg = 'background', blend = 55 },
  FloatShadowThrough = { bg = 'background', blend = 85 },

  Cursor = { fg = 'background', bg = 'text_bright' },
  CursorIM = { link = 'Cursor' },
  lCursor = { link = 'Cursor' },
  TermCursor = { link = 'Cursor' },
  TermCursorNC = { fg = 'background', bg = 'text_subtle' },
  CursorColumn = { bg = 'surface' },
  CursorLine = { bg = 'surface' },
  CursorLineNr = { fg = 'primary', bg = 'surface', bold = true },
  CursorLineSign = { bg = 'surface' },
  CursorLineFold = { bg = 'surface' },
  LineNr = { fg = 'text_muted', bg = 'background' },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  SignColumn = { bg = 'background' },
  ColorColumn = { bg = 'surface' },
  Conceal = { fg = 'text_subtle' },

  Visual = { bg = 'visual' },
  VisualNOS = { bg = 'visual' },
  Search = { fg = 'background', bg = 'warning' },
  IncSearch = { fg = 'background', bg = 'primary', bold = true },
  CurSearch = { link = 'IncSearch' },
  Substitute = { fg = 'background', bg = 'tertiary' },
  MatchParen = { fg = 'primary', bold = true, underline = true },

  Pmenu = { fg = 'text', bg = 'container' },
  PmenuSel = { fg = 'text_bright', bg = 'overlay' },
  PmenuKind = { fg = 'warning', bg = 'container' },
  PmenuKindSel = { fg = 'warning', bg = 'overlay' },
  PmenuExtra = { fg = 'text_subtle', bg = 'container' },
  PmenuExtraSel = { fg = 'text_secondary', bg = 'overlay' },
  PmenuSbar = { bg = 'surface' },
  PmenuThumb = { bg = 'overlay' },
  PmenuMatch = { fg = 'primary', bg = 'container', bold = true },
  PmenuMatchSel = { fg = 'primary', bg = 'overlay', bold = true },
  ComplMatchIns = { fg = 'text_subtle' },
  SnippetTabstop = { bg = 'surface' },

  StatusLine = { fg = 'text_bright', bg = 'overlay' },
  StatusLineNC = { fg = 'text_subtle', bg = 'surface' },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  TabLine = { fg = 'text', bg = 'surface' },
  TabLineFill = { bg = 'container' },
  TabLineSel = { fg = 'text_bright', bg = 'overlay', bold = true },
  WinSeparator = { fg = 'text_muted' },
  VertSplit = { link = 'WinSeparator' },
  WinBar = { fg = 'text_secondary', bg = 'background', bold = true },
  WinBarNC = { fg = 'text_muted', bg = 'background' },
  ToolbarLine = { bg = 'container' },
  ToolbarButton = { fg = 'background', bg = 'info', bold = true },

  Folded = { fg = 'text_subtle', bg = 'surface' },
  FoldColumn = { fg = 'text_muted', bg = 'background' },
  QuickFixLine = { bg = 'surface', bold = true },
  qfLineNr = { fg = 'warning' },
  qfFileName = { fg = 'info' },

  Directory = { fg = 'info' },
  Title = { fg = 'tertiary', bold = true },
  Question = { fg = 'primary' },
  MoreMsg = { fg = 'quaternary' },
  ModeMsg = { fg = 'text_secondary', bold = true },
  WarningMsg = { fg = 'warning' },
  ErrorMsg = { fg = 'error', bold = true },
  MsgArea = { fg = 'text' },
  MsgSeparator = { fg = 'text_muted', bg = 'surface' },

  NonText = { fg = 'text_muted' },
  EndOfBuffer = { fg = 'text_muted', bg = 'background' },
  SpecialKey = { fg = 'text_muted' },
  Whitespace = { fg = 'text_muted' },
  WildMenu = { fg = 'background', bg = 'warning' },

  SpellBad = { undercurl = true, sp = 'error' },
  SpellCap = { undercurl = true, sp = 'info' },
  SpellLocal = { undercurl = true, sp = 'quaternary' },
  SpellRare = { undercurl = true, sp = 'tertiary' },

  Added = { fg = 'success' },
  Changed = { fg = 'quaternary' },
  Removed = { fg = 'error' },
  DiffAdd = { fg = 'success', bg = 'surface' },
  DiffChange = { fg = 'quaternary', bg = 'surface' },
  DiffDelete = { fg = 'error', bg = 'surface' },
  DiffText = { fg = 'warning', bg = 'overlay', bold = true },

  healthError = { fg = 'error' },
  healthSuccess = { fg = 'success' },
  healthWarning = { fg = 'warning' },
  NvimInternalError = { fg = 'background', bg = 'error' },
  RedrawDebugClear = { fg = 'background', bg = 'warning' },
  RedrawDebugComposed = { fg = 'background', bg = 'success' },
  RedrawDebugNormal = { reverse = true },
  RedrawDebugRecompose = { fg = 'background', bg = 'error' },
}
