return {
  markdownHeadingDelimiter = { fg = 'primary', bold = true },
  markdownH1 = { fg = 'primary', bold = true },
  markdownH2 = { fg = 'primary', bold = true },
  markdownH3 = { fg = 'warning', bold = true },
  markdownH4 = { fg = 'secondary', bold = true },
  markdownH5 = { fg = 'info', bold = true },
  markdownH6 = { fg = 'tertiary', bold = true },
  markdownCode = { fg = 'text_bright', bg = 'container' },
  markdownCodeBlock = { fg = 'text_bright', bg = 'container' },
  markdownCodeDelimiter = { fg = 'text_subtle' },
  markdownLinkText = { fg = 'info', underline = true },
  markdownUrl = { fg = 'info', underline = true },
  markdownLinkTextDelimiter = { fg = 'text_muted' },
  markdownLinkDelimiter = { fg = 'text_muted' },
  markdownListMarker = { fg = 'secondary' },
  markdownOrderedListMarker = { fg = 'secondary' },
  markdownBlockquote = { fg = 'warning' },
  markdownRule = { fg = 'warning' },
  markdownBold = { bold = true },
  markdownItalic = { italic = true },
  markdownBoldItalic = { bold = true, italic = true },
  markdownEscape = { fg = 'text_bright' },
  markdownError = { fg = 'error' },

  jsonKeyword = { fg = 'text_secondary' },
  jsonQuote = { fg = 'text_subtle' },
  jsonBraces = { fg = 'text_muted' },
  jsonNull = { fg = 'primary' },
  jsonBoolean = { fg = 'primary' },
  yamlKeyValueDelimiter = { fg = 'text_muted' },
  yamlBlockCollectionItemStart = { fg = 'secondary' },
  yamlAnchor = { fg = 'warning' },
  yamlAlias = { fg = 'warning' },
  yamlDocumentStart = { fg = 'text_muted' },
  yamlTag = { fg = 'info' },
  tomlKey = { fg = 'text_secondary' },
  tomlTable = { fg = 'info', bold = true },
  tomlTableArray = { fg = 'info', bold = true },
  tomlDate = { fg = 'primary' },
  tomlBoolean = { fg = 'primary' },
  dosiniLabel = { fg = 'info', bold = true },

  htmlTag = { fg = 'text_muted' },
  htmlEndTag = { fg = 'text_muted' },
  htmlTagName = { fg = 'info', italic = true },
  htmlSpecialTagName = { fg = 'info', italic = true },
  htmlArg = { fg = 'warning' },
  htmlLink = { fg = 'info', underline = true },
  htmlBold = { bold = true },
  htmlItalic = { italic = true },
  cssBraces = { fg = 'text_muted' },
  cssClassName = { fg = 'text_secondary' },
  cssIdentifier = { fg = 'text_secondary' },
  cssProp = { fg = 'text_secondary' },
  cssFunctionName = { fg = 'info', bold = true },
  cssColor = { fg = 'primary' },
  cssUnitDecorators = { fg = 'warning' },
  cssImportant = { fg = 'tertiary', bold = true },

  luaFuncCall = { fg = 'info', bold = true },
  luaFunction = { fg = 'primary' },
  luaTable = { fg = 'text_bright' },
  luaConstant = { fg = 'primary' },
  luaBuiltIn = { fg = 'tertiary', italic = true },
  luaDocTag = { fg = 'text_subtle', italic = true },
  luaDocIdentifier = { fg = 'text_subtle', italic = true },

  goPackage = { fg = 'primary' },
  goImport = { fg = 'primary' },
  goVar = { fg = 'primary' },
  goConst = { fg = 'primary' },
  goType = { fg = 'primary' },
  goBuiltins = { fg = 'tertiary', bold = true },
  goFormatSpecifier = { fg = 'text_bright' },
  goGenerateVariables = { fg = 'text_bright', italic = true },
  ['@comment.directive.go'] = { fg = 'tertiary', italic = true },
  ['@comment.documentation.go'] = { fg = 'text_subtle', italic = true },
  ['@lsp.type.namespace.go'] = { fg = 'info', bold = true },

  pythonBuiltin = { fg = 'tertiary', bold = true },
  pythonFunction = { fg = 'info', bold = true },
  pythonDecorator = { fg = 'warning', italic = true },
  pythonDecoratorName = { fg = 'warning', bold = true },
  pythonExceptions = { fg = 'warning', bold = true },
  pythonSelf = { fg = 'tertiary', italic = true },
  ['@variable.builtin.python'] = { fg = 'tertiary', italic = true },
  ['@function.builtin.python'] = { fg = 'tertiary', bold = true },

  rustAttribute = { fg = 'warning', italic = true },
  rustDerive = { fg = 'tertiary', italic = true },
  rustMacro = { fg = 'tertiary', italic = true },
  rustModPath = { fg = 'info', bold = true },
  rustSelf = { fg = 'tertiary', italic = true },
  rustEnum = { fg = 'warning', italic = true },
  rustEnumVariant = { fg = 'primary' },
  ['@attribute.rust'] = { fg = 'warning', italic = true },
  ['@function.macro.rust'] = { fg = 'tertiary', italic = true },
  ['@lsp.type.enumMember.rust'] = { fg = 'primary' },

  shShellVariables = { fg = 'text_bright', italic = true },
  shVariable = { fg = 'text' },
  shFunction = { fg = 'info', bold = true },
  shFunctionKey = { fg = 'primary' },
  shDeref = { fg = 'quaternary' },
  shCommandSub = { fg = 'info', bold = true },
  shQuote = { fg = 'secondary' },
  shOption = { fg = 'quaternary' },

  javascriptBraces = { fg = 'text_muted' },
  javascriptFunction = { fg = 'primary' },
  javascriptIdentifier = { fg = 'text' },
  javascriptNull = { fg = 'primary' },
  javascriptNumber = { fg = 'primary' },
  javascriptObjectLabel = { fg = 'text_secondary' },
  javascriptTemplate = { fg = 'secondary' },
  typescriptTypeReference = { fg = 'warning', italic = true },
  typescriptBraces = { fg = 'text_muted' },
  typescriptFuncKeyword = { fg = 'primary' },
  ['@lsp.type.property.typescript'] = { fg = 'text_secondary' },
  ['@lsp.type.property.javascript'] = { fg = 'text_secondary' },
}
