-- Generated by pnpm build in cinder-muted; do not edit.
-- Cinder Muted: one ember tone ramp derived from the Cinder Grove palette.
return {
  visual = '#46372f',
  background = '#16110f',
  container = '#1f1714',
  surface = '#281e19',
  overlay = '#624f46',
  text_muted = '#624f46',
  text_subtle = '#a78e82',
  text_secondary = '#b99f93',
  text = '#c9aea0',
  text_bright = '#eccfc1',
  primary = '#f09361',
  secondary = '#df8452',
  error = '#a45751',
  warning = '#ffa474',
  success = '#df8452',
  info = '#ac5621',
  purple = '#bd6532',
  cyan = '#ce7442',
}
